name = "cardano-foundation/cardano-template-and-ecosystem-monitoring"
version = "0.2.0"
compiler = "v1.1.17"
plutus = "v3"
description = "Aiken contracts for project 'cardano-foundation/cardano-template-and-ecosystem-monitoring/bet'"

[repository]
user = "cardano-foundation/cardano-template-and-ecosystem-monitoring"
project = "bet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.15"
source = "github"

[config]
