name = "cardano-foundation/cardano-template-and-ecosystem-monitoring/bet"
version = "0.2.0"
licences = ["Apache-2.0"]
description = "Aiken contracts for project 'cardano-foundation/cardano-template-and-ecosystem-monitoring/bet'"

[repository]
user = "cardano-foundation/cardano-template-and-ecosystem-monitoring"
project = "bet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"
